rules:
  property-sort-order: 0
  nesting-depth:
    - 1
    -
      max-depth: 6
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background-image
  mixins-before-declarations: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  indentation:
    - 1
    -
      size: 'tab'
  clean-import-paths:
    - 0
  pseudo-element:
    - 0
  force-pseudo-nesting:
    - 0
  no-important:
    - 0
  class-name-format:
    - 1
    -
      ignore: 
files:
  ignore:
